!-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
! MODEL
!	   BFM - Biogeochemical Flux Model
!
! MODULE
!   set_var_info_bfm
!
! FILE
!   set_var_info_bfm
!
! DESCRIPTION
!  This subroutine provides information on the variables. To be used
!  when storing data in NetCDF files.
!  This file is produced by a procedure from a file which include all
!  definitions of global variables and state variables  and a proto-file
!
!
! AUTHORS
!    Piet Ruardij
!
! CHANGE_LOG
!   ---
!
! COPYING
!
!   Copyright (C) 2015 BFM System Team (bfm_st@lists.cmcc.it)
!   Copyright (C) 2006 P. Ruardij  (rua@nioz.nl)
!
!   This program is free software; you can redistribute it and/or modify
!   it under the terms of the GNU General Public License as published by
!   the Free Software Foundation;
!   This program is distributed in the hope that it will be useful,
!   but WITHOUT ANY WARRANTY; without even the implied warranty of
!   MERCHANTEABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!   GNU General Public License for more details.
!
!-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
!
!
!

subroutine set_var_info_bfm

#ifdef BFM_GOTM
  use mem
  use bio_var, only: var_names,var_long,var_units
  use bio_var, only: stPelStateS,stPelDiagS,stPelFluxS,stBenStateS,stBenDiagS,stBenFluxS
  use bio_var, only: stPelStateE,stPelDiagE,stPelFluxE,stBenStateE,stBenDiagE,stBenFluxE
#else
  use api_bfm
#endif


!
! 3d variables description:
!
   var_names(1)="O2o" ! ok
   var_long(1)="Oxygen"
   var_units(1)="mmol O2/m3"
   var_names(2)="N1p" ! ok
   var_long(2)="Phosphate"
   var_units(2)="mmol P/m3"
   var_names(3)="N3n" ! ok
   var_long(3)="Nitrate"
   var_units(3)="mmol N/m3"
   var_names(4)="N4n" ! ok
   var_long(4)="Ammonium"
   var_units(4)="mmol N/m3"
   var_names(5)="O4n" ! ok
   var_long(5)="NitrogenSink"
   var_units(5)="mmol N/m3"
   var_names(6)="N5s" ! ok SiOH4
   var_long(6)="Silicate"
   var_units(6)="mmol Si/m3"
   var_names(7)="N6r" ! ok
   var_long(7)="Reduction Equivalents"
   var_units(7)="mmol S--/m3"
   var_names(8)="B1c" ! ok
   var_long(8)="Aerobic and Anaerobic Bacteria"
   var_units(8)="mg C/m3"
   var_names(9)="B1n" ! ok
   var_long(9)="Aerobic and Anaerobic Bacteria"
   var_units(9)="mmol N/m3"
   var_names(10)="B1p" ! ok
   var_long(10)="Aerobic and Anaerobic Bacteria"
   var_units(10)="mmol P/m3"
   var_names(11)="P1c" ! ok
   var_long(11)="Diatoms"
   var_units(11)="mg C/m3"
   var_names(12)="P1n" ! ok
   var_long(12)="Diatoms"
   var_units(12)="mmol N/m3"
   var_names(13)="P1p" ! ok
   var_long(13)="Diatoms"
   var_units(13)="mmol P/m3"
   var_names(14)="P1l" ! ok
   var_long(14)="Diatoms"
   var_units(14)="mg Chl/m3"
   var_names(15)="P1s" ! ok
   var_long(15)="Diatoms"
   var_units(15)="mmol Si/m3"
   var_names(16)="P2c" ! ok
   var_long(16)="Flagellates"
   var_units(16)="mg C/m3"
   var_names(17)="P2n" ! ok
   var_long(17)="Flagellates"
   var_units(17)="mmol N/m3"
   var_names(18)="P2p" ! ok
   var_long(18)="Flagellates"
   var_units(18)="mmol P/m3"
   var_names(19)="P2l" ! ok
   var_long(19)="Flagellates"
   var_units(19)="mg Chl/m3"
   var_names(20)="P3c" ! ok
   var_long(20)="PicoPhytoplankton"
   var_units(20)="mg C/m3"
   var_names(21)="P3n" ! ok
   var_long(21)="PicoPhytoplankton"
   var_units(21)="mmol N/m3"
   var_names(22)="P3p" ! ok
   var_long(22)="PicoPhytoplankton"
   var_units(22)="mmol P/m3"
   var_names(23)="P3l" ! ok
   var_long(23)="PicoPhytoplankton"
   var_units(23)="mg Chl/m3"
   var_names(24)="P4c" ! ok
   var_long(24)="Large Phytoplankton"
   var_units(24)="mg C/m3"
   var_names(25)="P4n" ! ok
   var_long(25)="Large Phytoplankton"
   var_units(25)="mmol N/m3"
   var_names(26)="P4p" ! ok
   var_long(26)="Large Phytoplankton"
   var_units(26)="mmol P/m3"
   var_names(27)="P4l" ! ok
   var_long(27)="Large Phytoplankton"
   var_units(27)="mg Chl/m3"
   var_names(28)="Z3c" ! ok
   var_long(28)="Carnivorous Mesozooplankton"
   var_units(28)="mg C/m3"
   var_names(29)="Z3n" ! ok
   var_long(29)="Carnivorous Mesozooplankton"
   var_units(29)="mmol N/m3"
   var_names(30)="Z3p" ! ok
   var_long(30)="Carnivorous Mesozooplankton"
   var_units(30)="mmol P/m3"
   var_names(31)="Z4c" ! ok
   var_long(31)="Omnivorous Mesozooplankton"
   var_units(31)="mg C/m3"
   var_names(32)="Z4n" ! ok
   var_long(32)="Omnivorous Mesozooplankton"
   var_units(32)="mmol N/m3"
   var_names(33)="Z4p" ! ok
   var_long(33)="Omnivorous Mesozooplankton"
   var_units(33)="mmol P/m3"
   var_names(34)="Z5c" ! ok
   var_long(34)="Microzooplankton"
   var_units(34)="mg C/m3"
   var_names(35)="Z5n" ! ok
   var_long(35)="Microzooplankton"
   var_units(35)="mmol N/m3"
   var_names(36)="Z5p" ! ok
   var_long(36)="Microzooplankton"
   var_units(36)="mmol P/m3"
   var_names(37)="Z6c" ! ok
   var_long(37)="Heterotrophic Nanoflagellates (HNAN)"
   var_units(37)="mg C/m3"
   var_names(38)="Z6n" ! ok
   var_long(38)="Heterotrophic Nanoflagellates (HNAN)"
   var_units(38)="mmol N/m3"
   var_names(39)="Z6p" ! ok
   var_long(39)="Heterotrophic Nanoflagellates (HNAN)"
   var_units(39)="mmol P/m3"
   var_names(40)="R1c" ! ok
   var_long(40)="Labile Dissolved Organic Matter"
   var_units(40)="mg C/m3"
   var_names(41)="R1n" ! ok
   var_long(41)="Labile Dissolved Organic Matter"
   var_units(41)="mmol N/m3"
   var_names(42)="R1p" ! ok
   var_long(42)="Labile Dissolved Organic Matter"
   var_units(42)="mmol P/m3"
   var_names(43)="R2c" ! ok
   var_long(43)="Semi-labile Dissolved Organic Carbon"
   var_units(43)="mg C/m3"
   var_names(44)="R3c" ! ok
   var_long(44)="Semi-refractory Dissolved Organic Carbon"
   var_units(44)="mg C/m3"
   var_names(45)="R6c" ! ok
   var_long(45)="Particulate Organic Matter"
   var_units(45)="mg C/m3"
   var_names(46)="R6n" ! ok
   var_long(46)="Particulate Organic Matter"
   var_units(46)="mmol N/m3"
   var_names(47)="R6p" ! ok
   var_long(47)="Particulate Organic Matter"
   var_units(47)="mmol P/m3"
   var_names(48)="R6s" ! ok 
   var_long(48)="Particulate Organic Matter"
   var_units(48)="mmol Si/m3"
   var_names(49)="O3c" ! ok
   var_long(49)="Dissolved Inorganic Carbon"
   var_units(49)="mg C/m3"
   var_names(50)="O3h" ! ok
   var_long(50)="Dissolved Inorganic Carbon"
   var_units(50)="mmol eq/m3"

   var_names(51)="ETW"
   var_long(51)="temperature"
   var_units(51)="C"
   var_names(52)="ESW"
   var_long(52)="Salinity"
   var_units(52)="-"
   var_names(53)="ERHO"
   var_long(53)="Seawater Density"
   var_units(53)="kg/m3"
   var_names(54)="EIR"
   var_long(54)="Irradiance"
   var_units(54)="uE/m2/s"
   var_names(55)="ESS"
   var_long(55)="Suspended Sediments"
   var_units(55)="g/m3"
   var_names(56)="EPR"
   var_long(56)="Water Pressure"
   var_units(56)="dbar"
   var_names(57)="Depth"
   var_long(57)="Gridpoint Depth"
   var_units(57)="m"
   var_names(58)="Volume"
   var_long(58)="Gridpoint Volume"
   var_units(58)="m3"
   var_names(59)="DIC"
   var_long(59)="Dissolved Inorganic Carbon"
   var_units(59)="umol/kg"
   var_names(60)="Area"
   var_long(60)="Gridpoint Area"
   var_units(60)="m2"
   var_names(61)="CO2"
   var_long(61)="CO2(aq)"
   var_units(61)="umol/kg"
   var_names(62)="pCO2"
   var_long(62)="Oceanic pCO2"
   var_units(62)="uatm"
   var_names(63)="HCO3"
   var_long(63)="Bicarbonate"
   var_units(63)="umol/kg"
   var_names(64)="CO3"
   var_long(64)="Carbonate"
   var_units(64)="umol/kg"
   var_names(65)="ALK"
   var_long(65)="Alkalinity"
   var_units(65)="umol eq/kg"
   var_names(66)="pH"
   var_long(66)="pH"
   var_units(66)="-"
   var_names(67)="OCalc"
   var_long(67)="Saturation state of Calcite"
   var_units(67)="-"
   var_names(68)="OArag"
   var_long(68)="Saturation state of Aragonite"
   var_units(68)="-"
   var_names(69)="totpelc"
   var_long(69)="Total Mass in Pelagic"
   var_units(69)="g C"
   var_names(70)="totpeln"
   var_long(70)="Total Mass in Pelagic"
   var_units(70)="g N"
   var_names(71)="totpelp"
   var_long(71)="Total Mass in Pelagic"
   var_units(71)="g P"
   var_names(72)="totpels"
   var_long(72)="Total Mass in Pelagic"
   var_units(72)="g Si"
   var_names(73)="cxoO2"
   var_long(73)="Oxygen Saturation"
   var_units(73)="mmol O2/m3"
   var_names(74)="eO2mO2"
   var_long(74)="Relative Oxygen saturation"
   var_units(74)="-"
   var_names(75)="Chla"
   var_long(75)="Chlorophyll-a"
   var_units(75)="mg Chl/m3"
   var_names(76)="flPTN6r"
   var_long(76)="Pelagic Anaerobic Mineralization Rate"
   var_units(76)="mmol O2/m3/d"
   var_names(77)="flN3O4n"
   var_long(77)="Pelagic Denitrification Rate"
   var_units(77)="mmol N/m3/d"
   var_names(78)="flN4N3n"
   var_long(78)="Pelagic Nitrification Rate"
   var_units(78)="mmol N/m3/d"
   var_names(79)="sediR2"
   var_long(79)="Detritus sedimentation rate"
   var_units(79)="m/d"
   var_names(80)="sediR6"
   var_long(80)="Detritus sedimentation rate"
   var_units(80)="m/d"
   var_names(81)="xEPS"
   var_long(81)="Total Extinction Coefficient"
   var_units(81)="1/m"
   var_names(82)="ABIO_eps"
   var_long(82)="Abiotic Extinction Coefficient"
   var_units(82)="1/m"

   var_names(83)="qpcPPY(iiP1)"
   var_long(83)="Quotum P/C in Phytoplankton"
   var_units(83)="mmol P/mg C"
   var_names(84)="qpcPPY(iiP2)"
   var_long(84)="Quotum P/C in Phytoplankton"
   var_units(84)="mmol P/mg C"
   var_names(85)="qpcPPY(iiP3)"
   var_long(85)="Quotum P/C in Phytoplankton"
   var_units(85)="mmol P/mg C"
   var_names(86)="qpcPPY(iiP4)"
   var_long(86)="Quotum P/C in Phytoplankton"
   var_units(86)="mmol P/mg C"
   var_names(87)="qncPPY(iiP1)"
   var_long(87)="Quotum N/C in Phytoplankton"
   var_units(87)="mmol N/mg C"
   var_names(88)="qncPPY(iiP2)"
   var_long(88)="Quotum N/C in Phytoplankton"
   var_units(88)="mmol N/mg C"
   var_names(89)="qncPPY(iiP3)"
   var_long(89)="Quotum N/C in Phytoplankton"
   var_units(89)="mmol N/mg C"
   var_names(90)="qncPPY(iiP4)"
   var_long(90)="Quotum N/C in Phytoplankton"
   var_units(90)="mmol N/mg C"
   var_names(91)="qscPPY(iiP1)"
   var_long(91)="Quotum Si/C in Phytoplankton"
   var_units(91)="mmol Si/mg C"
   var_names(92)="qscPPY(iiP2)"
   var_long(92)="Quotum Si/C in Phytoplankton"
   var_units(92)="mmol Si/mg C"
   var_names(93)="qscPPY(iiP3)"
   var_long(93)="Quotum Si/C in Phytoplankton"
   var_units(93)="mmol Si/mg C"
   var_names(94)="qscPPY(iiP4)"
   var_long(94)="Quotum Si/C in Phytoplankton"
   var_units(94)="mmol Si/mg C"
   var_names(95)="qlcPPY(iiP1)"
   var_long(95)="Quotum Chl/C in Phytoplankton"
   var_units(95)="mg Chl /mg C"
   var_names(96)="qlcPPY(iiP2)"
   var_long(96)="Quotum Chl/C in Phytoplankton"
   var_units(96)="mg Chl /mg C"
   var_names(97)="qlcPPY(iiP3)"
   var_long(97)="Quotum Chl/C in Phytoplankton"
   var_units(97)="mg Chl /mg C"
   var_names(98)="qlcPPY(iiP4)"
   var_long(98)="Quotum Chl/C in Phytoplankton"
   var_units(98)="mg Chl /mg C"
   var_names(99)="qpcMEZ(iiZ3)"
   var_long(99)="Quotum P/C in Mesozooplankton"
   var_units(99)="mmol P/mg C"
   var_names(100)="qpcMEZ(iiZ4)"
   var_long(100)="Quotum P/C in Mesozooplankton"
   var_units(100)="mmol P/mg C"
   var_names(101)="qncMEZ(iiZ3)"
   var_long(101)="Quotum N/C in Mesozooplankton"
   var_units(101)="mmol N/mg C"
   var_names(102)="qncMEZ(iiZ4)"
   var_long(102)="Quotum N/C in Mesozooplankton"
   var_units(102)="mmol N/mg C"
   var_names(103)="qpcMIZ(iiZ5)"
   var_long(103)="Quotum P/C in Z5(MicroZooPlankton)"
   var_units(103)="mmol P/mg C"
   var_names(104)="qpcMIZ(iiZ6)"
   var_long(104)="Quotum P/C in Z6(MicroZooPlankton)"
   var_units(104)="mmol P/mg C"
   var_names(105)="qncMIZ(iiZ5)"
   var_long(105)="Quotum N/C in Z5(MicroZooPlankton)"
   var_units(105)="mmol N/mg C"
   var_names(106)="qncMIZ(iiZ6)"
   var_long(106)="Quotum N/C in Z6(MicroZooPlankton)"
   var_units(106)="mmol N/mg C"
   var_names(107)="qpcOMT(iiR1)"
   var_long(107)="Quotum P/C in Organic Matter"
   var_units(107)="mmol N/mg C"
   var_names(108)="qpcOMT(iiR2)"
   var_long(108)="Quotum P/C in Organic Matter"
   var_units(108)="mmol N/mg C"
   var_names(109)="qpcOMT(iiR3)"
   var_long(109)="Quotum P/C in Organic Matter"
   var_units(109)="mmol N/mg C"
   var_names(110)="qpcOMT(iiR6)"
   var_long(110)="Quotum P/C in Organic Matter"
   var_units(110)="mmol N/mg C"
   var_names(111)="qncOMT(iiR1)"
   var_long(111)="Quotum N/C in Organic Matter"
   var_units(111)="mmol P/mg C"
   var_names(112)="qncOMT(iiR2)"
   var_long(112)="Quotum N/C in Organic Matter"
   var_units(112)="mmol P/mg C"
   var_names(113)="qncOMT(iiR3)"
   var_long(113)="Quotum N/C in Organic Matter"
   var_units(113)="mmol P/mg C"
   var_names(114)="qncOMT(iiR6)"
   var_long(114)="Quotum N/C in Organic Matter"
   var_units(114)="mmol P/mg C"
   var_names(115)="qscOMT(iiR1)"
   var_long(115)="Quotum Si/C in Organic Matter"
   var_units(115)="mmol Si/mg C"
   var_names(116)="qscOMT(iiR2)"
   var_long(116)="Quotum Si/C in Organic Matter"
   var_units(116)="mmol Si/mg C"
   var_names(117)="qscOMT(iiR3)"
   var_long(117)="Quotum Si/C in Organic Matter"
   var_units(117)="mmol Si/mg C"
   var_names(118)="qscOMT(iiR6)"
   var_long(118)="Quotum Si/C in Organic Matter"
   var_units(118)="mmol Si/mg C"
   var_names(119)="qpcPBA(iiB1)"
   var_long(119)="Quotum P/C in Pelagic Bacteria"
   var_units(119)="mmol P/mg C"
   var_names(120)="qncPBA(iiB1)"
   var_long(120)="Quotum N/C in Pelagic Bacteria"
   var_units(120)="mmol N/mg C"
   var_names(121)="sediPPY(iiP1)"
   var_long(121)="P1(PhytoPlankton) sedimentation rate"
   var_units(121)="m/d"
   var_names(122)="sediPPY(iiP2)"
   var_long(122)="P2(PhytoPlankton) sedimentation rate"
   var_units(122)="m/d"
   var_names(123)="sediPPY(iiP3)"
   var_long(123)="P3(PhytoPlankton) sedimentation rate"
   var_units(123)="m/d"
   var_names(124)="sediPPY(iiP4)"
   var_long(124)="P4(PhytoPlankton) sedimentation rate"
   var_units(124)="m/d"
   var_names(125)="sediMIZ(iiZ5)"
   var_long(125)="Z5(MicroZooPlankton) sedimentation rate"
   var_units(125)="m/d"
   var_names(126)="sediMIZ(iiZ6)"
   var_long(126)="Z6(MicroZooPlankton) sedimentation rate"
   var_units(126)="m/d"
   var_names(127)="sediMEZ(iiZ3)"
   var_long(127)="Z3(MesoZooPlankton) sedimentation rate"
   var_units(127)="m/d"
   var_names(128)="sediMEZ(iiZ4)"
   var_long(128)="Z4(MesoZooPlankton) sedimentation rate"
   var_units(128)="m/d"
   var_names(129)="sunPPY(iiP1)"
   var_long(129)="Specific Net Production of P1(PhytoPlankton)"
   var_units(129)="1/d"
   var_names(130)="sunPPY(iiP2)"
   var_long(130)="Specific Net Production of P2(PhytoPlankton)"
   var_units(130)="1/d"
   var_names(131)="sunPPY(iiP3)"
   var_long(131)="Specific Net Production of P3(PhytoPlankton)"
   var_units(131)="1/d"
   var_names(132)="sunPPY(iiP4)"
   var_long(132)="Specific Net Production of P4(PhytoPlankton)"
   var_units(132)="1/d"
   var_names(133)="eiPPY(iiP1)"
   var_long(133)="Regulating Factor for Light in P1(PhytoPlankton)"
   var_units(133)="-"
   var_names(134)="eiPPY(iiP2)"
   var_long(134)="Regulating Factor for Light in P2(PhytoPlankton)"
   var_units(134)="-"
   var_names(135)="eiPPY(iiP3)"
   var_long(135)="Regulating Factor for Light in P3(PhytoPlankton)"
   var_units(135)="-"
   var_names(136)="eiPPY(iiP4)"
   var_long(136)="Regulating Factor for Light in P4(PhytoPlankton)"
   var_units(136)="-"
   var_names(137)="ELiPPY(iiP1)"
   var_long(137)="Optimal light in P1(PhytoPlankton)"
   var_units(137)="W/m2"
   var_names(138)="ELiPPY(iiP2)"
   var_long(138)="Optimal light in P2(PhytoPlankton)"
   var_units(138)="W/m2"
   var_names(139)="ELiPPY(iiP3)"
   var_long(139)="Optimal light in P3(PhytoPlankton)"
   var_units(139)="W/m2"
   var_names(140)="ELiPPY(iiP4)"
   var_long(140)="Optimal light in P4(PhytoPlankton)"
   var_units(140)="W/m2"

   var_names(141)="ruPTc"
   var_long(141)="Gross Primary Production"
   var_units(141)="mg C/m3/d"
   var_names(142)="resPP"
   var_long(142)="Respiration of phytoplankton"
   var_units(142)="mg C/m3/d"
   var_names(143)="resZT"
   var_long(143)="Respiration of zooplankton"
   var_units(143)="mg C/m3/d"
   var_names(144)="ruPTn"
   var_long(144)="net nutrient uptake"
   var_units(144)="mmoln /m3/d"
   var_names(145)="ruPTp"
   var_long(145)="net phosphate uptake"
   var_units(145)="mmol P /m3/d"
   var_names(146)="exPP"
   var_long(146)="C excretion from phytoplankton"
   var_units(146)="mg C/m3/d"
   var_names(147)="ruZTc"
   var_long(147)="gross secondary production"
   var_units(147)="mg C/m3/d"
   var_names(148)="netZTc"
   var_long(148)="net secondary production"
   var_units(148)="mg C/m3/d"
   var_names(149)="rrPTo"
   var_long(149)="pelagic respiration"
   var_units(149)="mmol O2/m3/d"
   var_names(150)="rePTn"
   var_long(150)="pelagic mineralization"
   var_units(150)="mmol N/m3/d"
   var_names(151)="rePTp"
   var_long(151)="pelagic mineralization"
   var_units(151)="mmol P /m3/d"
   var_names(152)="reBn"
   var_long(152)="bacterial mineralization"
   var_units(152)="mmol N/m3/d"
   var_names(153)="ruBn"
   var_long(153)="bacterial uptake"
   var_units(153)="mmol N/m3/d"
   var_names(154)="fR2B1c"
   var_long(154)="TEP uptake by bacteria"
   var_units(154)="mg C/m3/d"
   var_names(155)="fP1Z4c"
   var_long(155)="diatom grazing by omniv.zooplankton"
   var_units(155)="mg C/m3/d"


!
!2d Pelagic variables description
   var_names(156)="EPCO2air"
   var_long(156)="Atmospheric CO2 Partial Pressure"
   var_units(156)="uatm"
   var_names(157)="CO2airflux"
   var_long(157)="Sea-air CO2 Flux"
   var_units(157)="mmol/m2/d"
   var_names(158)="Area2d"
   var_long(158)="2-D Gridpoint Area"
   var_units(158)="m2"
   var_names(159)="ThereIsLight"
   var_long(159)="Switch for day/night cycle"
   var_units(159)="-"
   var_names(160)="SUNQ"
   var_long(160)="Daylength in hours"
   var_units(160)="h"
   var_names(161)="totsysc"
   var_long(161)="total mass"
   var_units(161)="g C"
   var_names(162)="totsysn"
   var_long(162)="total mass"
   var_units(162)="g N"
   var_names(163)="EWIND"
   var_long(163)="Wind speed"
   var_units(163)="m/s"
   var_names(164)="totsysp"
   var_long(164)="total mass"
   var_units(164)="g P"
   var_names(165)="totsyss"
   var_long(165)="total mass"
   var_units(165)="g Si"
   var_names(166)="EICE"
   var_long(166)="Sea-ice fraction"
   var_units(166)="-"

!
! surface
!
   var_names(167)="jsurO2o"
   var_long(167)="flux of Oxygen at SURFACE"
   var_units(167)="mmol O2/m2/day"
   var_names(168)="jsurN1p"
   var_long(168)="flux of Phosphate at SURFACE"
   var_units(168)="mmol P/m2/day"
   var_names(169)="jsurN3n"
   var_long(169)="flux of Nitrate at SURFACE"
   var_units(169)="mmol N/m2/day"
   var_names(170)="jsurN4n"
   var_long(170)="flux of Ammonium at SURFACE"
   var_units(170)="mmol N/m2/day"
   var_names(171)="jsurO4n"
   var_long(171)="flux of NitrogenSink at SURFACE"
   var_units(171)="mmol N/m2/day"
   var_names(172)="jsurN5s"
   var_long(172)="flux of Silicate at SURFACE"
   var_units(172)="mmol Si/m2/day"
   var_names(173)="jsurN6r"
   var_long(173)="flux of Reduction Equivalents at SURFACE"
   var_units(173)="mmol S--/m2/day"
   var_names(174)="jsurB1c"
   var_long(174)="flux of Aerobic and Anaerobic Bacteria at SURFACE"
   var_units(174)="mg C/m2/day"
   var_names(175)="jsurB1n"
   var_long(175)="flux of Aerobic and Anaerobic Bacteria at SURFACE"
   var_units(175)="mmol N/m2/day"
   var_names(176)="jsurB1p"
   var_long(176)="flux of Aerobic and Anaerobic Bacteria at SURFACE"
   var_units(176)="mmol P/m2/day"
   var_names(177)="jsurP1c"
   var_long(177)="flux of Diatoms at SURFACE"
   var_units(177)="mg C/m2/day"
   var_names(178)="jsurP1n"
   var_long(178)="flux of Diatoms at SURFACE"
   var_units(178)="mmol N/m2/day"
   var_names(179)="jsurP1p"
   var_long(179)="flux of Diatoms at SURFACE"
   var_units(179)="mmol P/m2/day"
   var_names(180)="jsurP1l"
   var_long(180)="flux of Diatoms at SURFACE"
   var_units(180)="mg Chl/m2/day"
   var_names(181)="jsurP1s"
   var_long(181)="flux of Diatoms at SURFACE"
   var_units(181)="mmol Si/m2/day"
   var_names(182)="jsurP2c"
   var_long(182)="flux of Flagellates at SURFACE"
   var_units(182)="mg C/m2/day"
   var_names(183)="jsurP2n"
   var_long(183)="flux of Flagellates at SURFACE"
   var_units(183)="mmol N/m2/day"
   var_names(184)="jsurP2p"
   var_long(184)="flux of Flagellates at SURFACE"
   var_units(184)="mmol P/m2/day"
   var_names(185)="jsurP2l"
   var_long(185)="flux of Flagellates at SURFACE"
   var_units(185)="mg Chl/m2/day"
   var_names(186)="jsurP3c"
   var_long(186)="flux of PicoPhytoplankton at SURFACE"
   var_units(186)="mg C/m2/day"
   var_names(187)="jsurP3n"
   var_long(187)="flux of PicoPhytoplankton at SURFACE"
   var_units(187)="mmol N/m2/day"
   var_names(188)="jsurP3p"
   var_long(188)="flux of PicoPhytoplankton at SURFACE"
   var_units(188)="mmol P/m2/day"
   var_names(189)="jsurP3l"
   var_long(189)="flux of PicoPhytoplankton at SURFACE"
   var_units(189)="mg Chl/m2/day"
   var_names(190)="jsurP4c"
   var_long(190)="flux of Large Phytoplankton at SURFACE"
   var_units(190)="mg C/m2/day"
   var_names(191)="jsurP4n"
   var_long(191)="flux of Large Phytoplankton at SURFACE"
   var_units(191)="mmol N/m2/day"
   var_names(192)="jsurP4p"
   var_long(192)="flux of Large Phytoplankton at SURFACE"
   var_units(192)="mmol P/m2/day"
   var_names(193)="jsurP4l"
   var_long(193)="flux of Large Phytoplankton at SURFACE"
   var_units(193)="mg Chl/m2/day"
   var_names(194)="jsurZ3c"
   var_long(194)="flux of Carnivorous Mesozooplankton at SURFACE"
   var_units(194)="mg C/m2/day"
   var_names(195)="jsurZ3n"
   var_long(195)="flux of Carnivorous Mesozooplankton at SURFACE"
   var_units(195)="mmol N/m2/day"
   var_names(196)="jsurZ3p"
   var_long(196)="flux of Carnivorous Mesozooplankton at SURFACE"
   var_units(196)="mmol P/m2/day"
   var_names(197)="jsurZ4c"
   var_long(197)="flux of Omnivorous Mesozooplankton at SURFACE"
   var_units(197)="mg C/m2/day"
   var_names(198)="jsurZ4n"
   var_long(198)="flux of Omnivorous Mesozooplankton at SURFACE"
   var_units(198)="mmol N/m2/day"
   var_names(199)="jsurZ4p"
   var_long(199)="flux of Omnivorous Mesozooplankton at SURFACE"
   var_units(199)="mmol P/m2/day"
   var_names(200)="jsurZ5c"
   var_long(200)="flux of Microzooplankton at SURFACE"
   var_units(200)="mg C/m2/day"
   var_names(201)="jsurZ5n"
   var_long(201)="flux of Microzooplankton at SURFACE"
   var_units(201)="mmol N/m2/day"
   var_names(202)="jsurZ5p"
   var_long(202)="flux of Microzooplankton at SURFACE"
   var_units(202)="mmol P/m2/day"
   var_names(203)="jsurZ6c"
   var_long(203)="flux of Heterotrophic Nanoflagellates (HNAN) at SURFACE"
   var_units(203)="mg C/m2/day"
   var_names(204)="jsurZ6n"
   var_long(204)="flux of Heterotrophic Nanoflagellates (HNAN) at SURFACE"
   var_units(204)="mmol N/m2/day"
   var_names(205)="jsurZ6p"
   var_long(205)="flux of Heterotrophic Nanoflagellates (HNAN) at SURFACE"
   var_units(205)="mmol P/m2/day"
   var_names(206)="jsurR1c"
   var_long(206)="flux of Labile Dissolved Organic Matter at SURFACE"
   var_units(206)="mg C/m2/day"
   var_names(207)="jsurR1n"
   var_long(207)="flux of Labile Dissolved Organic Matter at SURFACE"
   var_units(207)="mmol N/m2/day"
   var_names(208)="jsurR1p"
   var_long(208)="flux of Labile Dissolved Organic Matter at SURFACE"
   var_units(208)="mmol P/m2/day"
   var_names(209)="jsurR2c"
   var_long(209)="flux of Semi-labile Dissolved Organic Carbon at SURFACE"
   var_units(209)="mg C/m2/day"
   var_names(210)="jsurR3c"
   var_long(210)="flux of Semi-refractory Dissolved Organic Carbon at SURFACE"
   var_units(210)="mg C/m2/day"
   var_names(211)="jsurR6c"
   var_long(211)="flux of Particulate Organic Matter at SURFACE"
   var_units(211)="mg C/m2/day"
   var_names(212)="jsurR6n"
   var_long(212)="flux of Particulate Organic Matter at SURFACE"
   var_units(212)="mmol N/m2/day"
   var_names(213)="jsurR6p"
   var_long(213)="flux of Particulate Organic Matter at SURFACE"
   var_units(213)="mmol P/m2/day"
   var_names(214)="jsurR6s"
   var_long(214)="flux of Particulate Organic Matter at SURFACE"
   var_units(214)="mmol Si/m2/day"
   var_names(215)="jsurO3c"
   var_long(215)="flux of Dissolved Inorganic Carbon at SURFACE"
   var_units(215)="mg C/m2/day"
   var_names(216)="jsurO3h"
   var_long(216)="flux of Dissolved Inorganic Carbon at SURFACE"
   var_units(216)="mmol eq/m2/day"

!
! bottom
!
   var_names(217)="jbotO2o"
   var_long(217)="flux of Oxygen at BOTTOM"
   var_units(217)="mmol O2/m2/day"
   var_names(218)="jbotN1p"
   var_long(218)="flux of Phosphate at BOTTOM"
   var_units(218)="mmol P/m2/day"
   var_names(219)="jbotN3n"
   var_long(219)="flux of Nitrate at BOTTOM"
   var_units(219)="mmol N/m2/day"
   var_names(220)="jbotN4n"
   var_long(220)="flux of Ammonium at BOTTOM"
   var_units(220)="mmol N/m2/day"
   var_names(221)="jbotO4n"
   var_long(221)="flux of NitrogenSink at BOTTOM"
   var_units(221)="mmol N/m2/day"
   var_names(222)="jbotN5s"
   var_long(222)="flux of Silicate at BOTTOM"
   var_units(222)="mmol Si/m2/day"
   var_names(223)="jbotN6r"
   var_long(223)="flux of Reduction Equivalents at BOTTOM"
   var_units(223)="mmol S--/m2/day"
   var_names(224)="jbotB1c"
   var_long(224)="flux of Aerobic and Anaerobic Bacteria at BOTTOM"
   var_units(224)="mg C/m2/day"
   var_names(225)="jbotB1n"
   var_long(225)="flux of Aerobic and Anaerobic Bacteria at BOTTOM"
   var_units(225)="mmol N/m2/day"
   var_names(226)="jbotB1p"
   var_long(226)="flux of Aerobic and Anaerobic Bacteria at BOTTOM"
   var_units(226)="mmol P/m2/day"
   var_names(227)="jbotP1c"
   var_long(227)="flux of Diatoms at BOTTOM"
   var_units(227)="mg C/m2/day"
   var_names(228)="jbotP1n"
   var_long(228)="flux of Diatoms at BOTTOM"
   var_units(228)="mmol N/m2/day"
   var_names(229)="jbotP1p"
   var_long(229)="flux of Diatoms at BOTTOM"
   var_units(229)="mmol P/m2/day"
   var_names(230)="jbotP1l"
   var_long(230)="flux of Diatoms at BOTTOM"
   var_units(230)="mg Chl/m2/day"
   var_names(231)="jbotP1s"
   var_long(231)="flux of Diatoms at BOTTOM"
   var_units(231)="mmol Si/m2/day"
   var_names(232)="jbotP2c"
   var_long(232)="flux of Flagellates at BOTTOM"
   var_units(232)="mg C/m2/day"
   var_names(233)="jbotP2n"
   var_long(233)="flux of Flagellates at BOTTOM"
   var_units(233)="mmol N/m2/day"
   var_names(234)="jbotP2p"
   var_long(234)="flux of Flagellates at BOTTOM"
   var_units(234)="mmol P/m2/day"
   var_names(235)="jbotP2l"
   var_long(235)="flux of Flagellates at BOTTOM"
   var_units(235)="mg Chl/m2/day"
   var_names(236)="jbotP3c"
   var_long(236)="flux of PicoPhytoplankton at BOTTOM"
   var_units(236)="mg C/m2/day"
   var_names(237)="jbotP3n"
   var_long(237)="flux of PicoPhytoplankton at BOTTOM"
   var_units(237)="mmol N/m2/day"
   var_names(238)="jbotP3p"
   var_long(238)="flux of PicoPhytoplankton at BOTTOM"
   var_units(238)="mmol P/m2/day"
   var_names(239)="jbotP3l"
   var_long(239)="flux of PicoPhytoplankton at BOTTOM"
   var_units(239)="mg Chl/m2/day"
   var_names(240)="jbotP4c"
   var_long(240)="flux of Large Phytoplankton at BOTTOM"
   var_units(240)="mg C/m2/day"
   var_names(241)="jbotP4n"
   var_long(241)="flux of Large Phytoplankton at BOTTOM"
   var_units(241)="mmol N/m2/day"
   var_names(242)="jbotP4p"
   var_long(242)="flux of Large Phytoplankton at BOTTOM"
   var_units(242)="mmol P/m2/day"
   var_names(243)="jbotP4l"
   var_long(243)="flux of Large Phytoplankton at BOTTOM"
   var_units(243)="mg Chl/m2/day"
   var_names(244)="jbotZ3c"
   var_long(244)="flux of Carnivorous Mesozooplankton at BOTTOM"
   var_units(244)="mg C/m2/day"
   var_names(245)="jbotZ3n"
   var_long(245)="flux of Carnivorous Mesozooplankton at BOTTOM"
   var_units(245)="mmol N/m2/day"
   var_names(246)="jbotZ3p"
   var_long(246)="flux of Carnivorous Mesozooplankton at BOTTOM"
   var_units(246)="mmol P/m2/day"
   var_names(247)="jbotZ4c"
   var_long(247)="flux of Omnivorous Mesozooplankton at BOTTOM"
   var_units(247)="mg C/m2/day"
   var_names(248)="jbotZ4n"
   var_long(248)="flux of Omnivorous Mesozooplankton at BOTTOM"
   var_units(248)="mmol N/m2/day"
   var_names(249)="jbotZ4p"
   var_long(249)="flux of Omnivorous Mesozooplankton at BOTTOM"
   var_units(249)="mmol P/m2/day"
   var_names(250)="jbotZ5c"
   var_long(250)="flux of Microzooplankton at BOTTOM"
   var_units(250)="mg C/m2/day"
   var_names(251)="jbotZ5n"
   var_long(251)="flux of Microzooplankton at BOTTOM"
   var_units(251)="mmol N/m2/day"
   var_names(252)="jbotZ5p"
   var_long(252)="flux of Microzooplankton at BOTTOM"
   var_units(252)="mmol P/m2/day"
   var_names(253)="jbotZ6c"
   var_long(253)="flux of Heterotrophic Nanoflagellates (HNAN) at BOTTOM"
   var_units(253)="mg C/m2/day"
   var_names(254)="jbotZ6n"
   var_long(254)="flux of Heterotrophic Nanoflagellates (HNAN) at BOTTOM"
   var_units(254)="mmol N/m2/day"
   var_names(255)="jbotZ6p"
   var_long(255)="flux of Heterotrophic Nanoflagellates (HNAN) at BOTTOM"
   var_units(255)="mmol P/m2/day"
   var_names(256)="jbotR1c"
   var_long(256)="flux of Labile Dissolved Organic Matter at BOTTOM"
   var_units(256)="mg C/m2/day"
   var_names(257)="jbotR1n"
   var_long(257)="flux of Labile Dissolved Organic Matter at BOTTOM"
   var_units(257)="mmol N/m2/day"
   var_names(258)="jbotR1p"
   var_long(258)="flux of Labile Dissolved Organic Matter at BOTTOM"
   var_units(258)="mmol P/m2/day"
   var_names(259)="jbotR2c"
   var_long(259)="flux of Semi-labile Dissolved Organic Carbon at BOTTOM"
   var_units(259)="mg C/m2/day"
   var_names(260)="jbotR3c"
   var_long(260)="flux of Semi-refractory Dissolved Organic Carbon at BOTTOM"
   var_units(260)="mg C/m2/day"
   var_names(261)="jbotR6c"
   var_long(261)="flux of Particulate Organic Matter at BOTTOM"
   var_units(261)="mg C/m2/day"
   var_names(262)="jbotR6n"
   var_long(262)="flux of Particulate Organic Matter at BOTTOM"
   var_units(262)="mmol N/m2/day"
   var_names(263)="jbotR6p"
   var_long(263)="flux of Particulate Organic Matter at BOTTOM"
   var_units(263)="mmol P/m2/day"
   var_names(264)="jbotR6s"
   var_long(264)="flux of Particulate Organic Matter at BOTTOM"
   var_units(264)="mmol Si/m2/day"
   var_names(265)="jbotO3c"
   var_long(265)="flux of Dissolved Inorganic Carbon at BOTTOM"
   var_units(265)="mg C/m2/day"
   var_names(266)="jbotO3h"
   var_long(266)="flux of Dissolved Inorganic Carbon at BOTTOM"
   var_units(266)="mmol eq/m2/day"

!
! river
!
   var_names(267)="jrivO2o"
   var_long(267)="flux of Oxygen at RIVER"
   var_units(267)="mmol O2/m2/day"
   var_names(268)="jrivN1p"
   var_long(268)="flux of Phosphate at RIVER"
   var_units(268)="mmol P/m2/day"
   var_names(269)="jrivN3n"
   var_long(269)="flux of Nitrate at RIVER"
   var_units(269)="mmol N/m2/day"
   var_names(270)="jrivN4n"
   var_long(270)="flux of Ammonium at RIVER"
   var_units(270)="mmol N/m2/day"
   var_names(271)="jrivO4n"
   var_long(271)="flux of NitrogenSink at RIVER"
   var_units(271)="mmol N/m2/day"
   var_names(272)="jrivN5s"
   var_long(272)="flux of Silicate at RIVER"
   var_units(272)="mmol Si/m2/day"
   var_names(273)="jrivN6r"
   var_long(273)="flux of Reduction Equivalents at RIVER"
   var_units(273)="mmol S--/m2/day"
   var_names(274)="jrivB1c"
   var_long(274)="flux of Aerobic and Anaerobic Bacteria at RIVER"
   var_units(274)="mg C/m2/day"
   var_names(275)="jrivB1n"
   var_long(275)="flux of Aerobic and Anaerobic Bacteria at RIVER"
   var_units(275)="mmol N/m2/day"
   var_names(276)="jrivB1p"
   var_long(276)="flux of Aerobic and Anaerobic Bacteria at RIVER"
   var_units(276)="mmol P/m2/day"
   var_names(277)="jrivP1c"
   var_long(277)="flux of Diatoms at RIVER"
   var_units(277)="mg C/m2/day"
   var_names(278)="jrivP1n"
   var_long(278)="flux of Diatoms at RIVER"
   var_units(278)="mmol N/m2/day"
   var_names(279)="jrivP1p"
   var_long(279)="flux of Diatoms at RIVER"
   var_units(279)="mmol P/m2/day"
   var_names(280)="jrivP1l"
   var_long(280)="flux of Diatoms at RIVER"
   var_units(280)="mg Chl/m2/day"
   var_names(281)="jrivP1s"
   var_long(281)="flux of Diatoms at RIVER"
   var_units(281)="mmol Si/m2/day"
   var_names(282)="jrivP2c"
   var_long(282)="flux of Flagellates at RIVER"
   var_units(282)="mg C/m2/day"
   var_names(283)="jrivP2n"
   var_long(283)="flux of Flagellates at RIVER"
   var_units(283)="mmol N/m2/day"
   var_names(284)="jrivP2p"
   var_long(284)="flux of Flagellates at RIVER"
   var_units(284)="mmol P/m2/day"
   var_names(285)="jrivP2l"
   var_long(285)="flux of Flagellates at RIVER"
   var_units(285)="mg Chl/m2/day"
   var_names(286)="jrivP3c"
   var_long(286)="flux of PicoPhytoplankton at RIVER"
   var_units(286)="mg C/m2/day"
   var_names(287)="jrivP3n"
   var_long(287)="flux of PicoPhytoplankton at RIVER"
   var_units(287)="mmol N/m2/day"
   var_names(288)="jrivP3p"
   var_long(288)="flux of PicoPhytoplankton at RIVER"
   var_units(288)="mmol P/m2/day"
   var_names(289)="jrivP3l"
   var_long(289)="flux of PicoPhytoplankton at RIVER"
   var_units(289)="mg Chl/m2/day"
   var_names(290)="jrivP4c"
   var_long(290)="flux of Large Phytoplankton at RIVER"
   var_units(290)="mg C/m2/day"
   var_names(291)="jrivP4n"
   var_long(291)="flux of Large Phytoplankton at RIVER"
   var_units(291)="mmol N/m2/day"
   var_names(292)="jrivP4p"
   var_long(292)="flux of Large Phytoplankton at RIVER"
   var_units(292)="mmol P/m2/day"
   var_names(293)="jrivP4l"
   var_long(293)="flux of Large Phytoplankton at RIVER"
   var_units(293)="mg Chl/m2/day"
   var_names(294)="jrivZ3c"
   var_long(294)="flux of Carnivorous Mesozooplankton at RIVER"
   var_units(294)="mg C/m2/day"
   var_names(295)="jrivZ3n"
   var_long(295)="flux of Carnivorous Mesozooplankton at RIVER"
   var_units(295)="mmol N/m2/day"
   var_names(296)="jrivZ3p"
   var_long(296)="flux of Carnivorous Mesozooplankton at RIVER"
   var_units(296)="mmol P/m2/day"
   var_names(297)="jrivZ4c"
   var_long(297)="flux of Omnivorous Mesozooplankton at RIVER"
   var_units(297)="mg C/m2/day"
   var_names(298)="jrivZ4n"
   var_long(298)="flux of Omnivorous Mesozooplankton at RIVER"
   var_units(298)="mmol N/m2/day"
   var_names(299)="jrivZ4p"
   var_long(299)="flux of Omnivorous Mesozooplankton at RIVER"
   var_units(299)="mmol P/m2/day"
   var_names(300)="jrivZ5c"
   var_long(300)="flux of Microzooplankton at RIVER"
   var_units(300)="mg C/m2/day"
   var_names(301)="jrivZ5n"
   var_long(301)="flux of Microzooplankton at RIVER"
   var_units(301)="mmol N/m2/day"
   var_names(302)="jrivZ5p"
   var_long(302)="flux of Microzooplankton at RIVER"
   var_units(302)="mmol P/m2/day"
   var_names(303)="jrivZ6c"
   var_long(303)="flux of Heterotrophic Nanoflagellates (HNAN) at RIVER"
   var_units(303)="mg C/m2/day"
   var_names(304)="jrivZ6n"
   var_long(304)="flux of Heterotrophic Nanoflagellates (HNAN) at RIVER"
   var_units(304)="mmol N/m2/day"
   var_names(305)="jrivZ6p"
   var_long(305)="flux of Heterotrophic Nanoflagellates (HNAN) at RIVER"
   var_units(305)="mmol P/m2/day"
   var_names(306)="jrivR1c"
   var_long(306)="flux of Labile Dissolved Organic Matter at RIVER"
   var_units(306)="mg C/m2/day"
   var_names(307)="jrivR1n"
   var_long(307)="flux of Labile Dissolved Organic Matter at RIVER"
   var_units(307)="mmol N/m2/day"
   var_names(308)="jrivR1p"
   var_long(308)="flux of Labile Dissolved Organic Matter at RIVER"
   var_units(308)="mmol P/m2/day"
   var_names(309)="jrivR2c"
   var_long(309)="flux of Semi-labile Dissolved Organic Carbon at RIVER"
   var_units(309)="mg C/m2/day"
   var_names(310)="jrivR3c"
   var_long(310)="flux of Semi-refractory Dissolved Organic Carbon at RIVER"
   var_units(310)="mg C/m2/day"
   var_names(311)="jrivR6c"
   var_long(311)="flux of Particulate Organic Matter at RIVER"
   var_units(311)="mg C/m2/day"
   var_names(312)="jrivR6n"
   var_long(312)="flux of Particulate Organic Matter at RIVER"
   var_units(312)="mmol N/m2/day"
   var_names(313)="jrivR6p"
   var_long(313)="flux of Particulate Organic Matter at RIVER"
   var_units(313)="mmol P/m2/day"
   var_names(314)="jrivR6s"
   var_long(314)="flux of Particulate Organic Matter at RIVER"
   var_units(314)="mmol Si/m2/day"
   var_names(315)="jrivO3c"
   var_long(315)="flux of Dissolved Inorganic Carbon at RIVER"
   var_units(315)="mg C/m2/day"
   var_names(316)="jrivO3h"
   var_long(316)="flux of Dissolved Inorganic Carbon at RIVER"
   var_units(316)="mmol eq/m2/day"


#ifdef INCLUDE_SEAICE
!
!2d SeaIce variables description




#endif

#ifdef INCLUDE_BEN
!
!2d Benthic variables description




#endif


!
!Index Pelagic
!
   stPelStart=1
   stPelEnd=316


   stPelStateS=1
   stPelStateE=50

   stPelDiagS=51
   stPelDiagE=140

   stPelFluxS=141
   stPelFluxE=155

   stPelDiag2dS=156
   stPelDiag2dE=166

   stPelSurS=167
   stPelSurE=216

   stPelBotS=217
   stPelBotE=266

   stPelRivS=267
   stPelRivE=316



#ifdef INCLUDE_SEAICE
!
!Index SeaIce
!
   stIceStart=317
   stIceEnd=316


   stIceStateS=317
   stIceStateE=316

   stIceDiag2dS=317
   stIceDiag2dE=316

   stIceFlux2dS=317
   stIceFlux2dE=316


#endif

#ifdef INCLUDE_BEN
!
!Index Benthic
!
   stBenStart=317
   stBenEnd=316


   stBenStateS=317
   stBenStateE=316

   stBenDiag2dS=317
   stBenDiag2dE=316

   stBenFlux2dS=317
   stBenFlux2dE=316


#endif


   stStart=1
   stEnd=316


end subroutine set_var_info_bfm
