name: Compiling ROMS

# https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release
# model taken from https://github.com/mockersf/kmanb/releases
# on: release

on:
  # Every sunday morning
  schedule:
    - cron: "0 0 * * 0"
  # Manually triggered
  workflow_dispatch:
  # Disabled right now, when a push is made on master.
jobs:
  build-linux:
    runs-on: ubuntu-22.04
    env:
      BOOST_INCDIR: "/usr/include"
      BOOST_LINK: "/usr/lib/x86_64-linux-gnu/libboost_serialization.a"
      NETCDF_INCDIR: "/usr/include"
      NETCDF_LIBDIR: "/usr/lib -lnetcdff"
      FORT: "gfortran"

    steps:
#      - name: Get the version
#        id: get_version
#        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Dependencies
        run: |
          sudo apt-get install -y libgdbm-dev libsnappy-dev make pkg-config rlwrap software-properties-common zlib1g-dev
          sudo apt-get install -y wget
          sudo apt-get install -y g++-11 clang-12
          sudo apt-get install -y g++ gcc gfortran
          sudo apt-get install -y cmake
          sudo apt-get install -y libgmp-dev
          sudo apt-get install -y libboost-dev libboost-mpi-dev libboost-serialization-dev
          sudo apt-get install -y autoconf autotools-dev libtool
          sudo apt-get install -y openmpi-bin libopenmpi-dev
          sudo apt-get install -y autoconf autotools-dev libtool
          sudo apt-get install -y libnetcdff-dev

      - name: Build test code
        run: |
          make
